server:
  port: 8111
spring:
  application:
    name: hysterix-service
eureka:
  client:
    serviceUrl:
        defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      preferIpAddress: true      
management:
  security:
    enabled: false